### 启动端口号
server:
  port: 8081
### 设置数据库
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/hrabbit_admin?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: root
    password: root
  mvc:
    static-path-pattern: /static/**
    view:
      prefix: /WEB-INF
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
### 配置mybatisPlus
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  typeAliasesPackage: com.hrabbit.admin.modual.system.bean
  configuration:
    map-underscore-to-camel-case: true
### 配置日志
log:
  path: logs

### 输出Sql日志
logging:
  level:
    com.hrabbit.admin.modual.system.mapper: debug

###beetl配置
beetl:
  #开始结束标签(yaml不允许@开头)
  delimiter-statement-start: \@
  delimiter-statement-end: null
  #自定义标签文件Root目录和后缀
  resource-tagroot: common/tags
  resource-tagsuffix: tag
  #是否检测文件变化,开发用true合适，但线上要改为false
  resource-auto-check: true

# 分页配置
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql